version: "2"

services:
  proc:
    image: ubuntu
    ports:
      - "9999:3000"
    restart: always
    volumes: 
      - /home/falcon/Documents/gin-forked/:/data
    tty: true
    
    #  bash -c "- apt-get update
    #  && apt-get install make wget git python python-pip -y
    #  && wget https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
    #  && tar -xvz go1.12.6.linux-amd64.tar.gz
    #  && mv go /usr/local
    #  && cd data/
    #  && make "
  gin:
    build:  /home/falcon/Documents/gin-forked 
    ports:
      - "9000:3000"

